version: "3.8"

services:
  app:
    build: .
    container_name: bosta_app
    command: sh -c "npx wait-on tcp:db:5432 && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.docker   # 👈 use docker-specific env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: bosta_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bosta
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # host:container
    env_file:
      - .env.docker   # optional (just keeps consistency)

volumes:
  db_data:
